### ISSUE TITLE
Remove eslint-babel

### ISSUE THREAD

**Issue by desandro** [fictivekin/eslint-config-fk#7]
<img width="332" alt="image" src="https://user-images.githubusercontent.com/85566/200389861-0f8d71e5-64aa-476a-8f97-f50abffc7366.png">
<img width="347" alt="image" src="https://user-images.githubusercontent.com/85566/200389915-44768149-7fbe-4622-96dd-dd6dafb83c23.png">
<img width="340" alt="image" src="https://user-images.githubusercontent.com/85566/200389979-c4194216-9d66-46a9-ae04-062f97c4ce41.png">

**Comment by desandro** [comment]
@theghostyced would love to hear your thoughts.

**Comment by theghostyced** [comment]
@desandro we can get rid of the `babel-eslint`. Done the research and it seems `next/core-web-vitals` comes with its own babel parser. Since we include the `next` eslint config as well in our projects, removing the `babel-parser` shouldn't affect the Next projects

References:
- https://github.com/vercel/next.js/blob/5e55c3c340c7f6bb25aebb161e554db3cbfcef90/packages/eslint-config-next/parser.js#L4
